//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }
    var text: text { .init(source: .init(bundle: bundle, tableName: "Text", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }
    func text(preferredLanguages: [String]) -> text {
      .init(source: .init(bundle: bundle, tableName: "Text", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 1 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// ja translation: 英会話
      ///
      /// Key: english
      ///
      /// Locales: ja
      var english: RswiftResources.StringResource { .init(key: "english", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }

    /// This `_R.string.text` struct is generated, and contains static references to 1 localization keys.
    struct text {
      let source: RswiftResources.StringResource.Source

      /// Value: 英会話
      ///
      /// Key: english
      var english: RswiftResources.StringResource { .init(key: "english", tableName: "Text", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 8 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `customBlack`.
    var customBlack: RswiftResources.ColorResource { .init(name: "customBlack", path: [], bundle: bundle) }

    /// Color `customBlue`.
    var customBlue: RswiftResources.ColorResource { .init(name: "customBlue", path: [], bundle: bundle) }

    /// Color `customGray`.
    var customGray: RswiftResources.ColorResource { .init(name: "customGray", path: [], bundle: bundle) }

    /// Color `customLightGray`.
    var customLightGray: RswiftResources.ColorResource { .init(name: "customLightGray", path: [], bundle: bundle) }

    /// Color `customLoadingGray`.
    var customLoadingGray: RswiftResources.ColorResource { .init(name: "customLoadingGray", path: [], bundle: bundle) }

    /// Color `customRed1`.
    var customRed1: RswiftResources.ColorResource { .init(name: "customRed1", path: [], bundle: bundle) }

    /// Color `customRed2`.
    var customRed2: RswiftResources.ColorResource { .init(name: "customRed2", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images, and 1 namespaces.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `LaunchImage`.
    var launchImage: RswiftResources.ImageResource { .init(name: "LaunchImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    var images: images { .init(bundle: bundle) }

    func images(bundle: Foundation.Bundle) -> images {
      .init(bundle: bundle)
    }


    /// This `_R.image.images` struct is generated, and contains static references to 0 imagess, and 5 namespaces.
    struct images {
      let bundle: Foundation.Bundle
      var category: category { .init(bundle: bundle) }
      var header: header { .init(bundle: bundle) }
      var onboarding: onboarding { .init(bundle: bundle) }
      var others: others { .init(bundle: bundle) }
      var setting: setting { .init(bundle: bundle) }

      func category(bundle: Foundation.Bundle) -> category {
        .init(bundle: bundle)
      }
      func header(bundle: Foundation.Bundle) -> header {
        .init(bundle: bundle)
      }
      func onboarding(bundle: Foundation.Bundle) -> onboarding {
        .init(bundle: bundle)
      }
      func others(bundle: Foundation.Bundle) -> others {
        .init(bundle: bundle)
      }
      func setting(bundle: Foundation.Bundle) -> setting {
        .init(bundle: bundle)
      }


      /// This `_R.image.images.category` struct is generated, and contains static references to 0 categorys, and 5 namespaces.
      struct category {
        let bundle: Foundation.Bundle
        var english: english { .init(bundle: bundle) }
        var finance: finance { .init(bundle: bundle) }
        var investment: investment { .init(bundle: bundle) }
        var law: law { .init(bundle: bundle) }
        var technology: technology { .init(bundle: bundle) }

        func english(bundle: Foundation.Bundle) -> english {
          .init(bundle: bundle)
        }
        func finance(bundle: Foundation.Bundle) -> finance {
          .init(bundle: bundle)
        }
        func investment(bundle: Foundation.Bundle) -> investment {
          .init(bundle: bundle)
        }
        func law(bundle: Foundation.Bundle) -> law {
          .init(bundle: bundle)
        }
        func technology(bundle: Foundation.Bundle) -> technology {
          .init(bundle: bundle)
        }


        /// This `_R.image.images.category.english` struct is generated, and contains static references to 5 englishs.
        struct english {
          let bundle: Foundation.Bundle

          /// Image `images/category/english/TOEFL`.
          var toefL: RswiftResources.ImageResource { .init(name: "images/category/english/TOEFL", path: ["images", "category", "english"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/english/TOEIC`.
          var toeiC: RswiftResources.ImageResource { .init(name: "images/category/english/TOEIC", path: ["images", "category", "english"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/english/alphabet`.
          var alphabet: RswiftResources.ImageResource { .init(name: "images/category/english/alphabet", path: ["images", "category", "english"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/english/english`.
          var english: RswiftResources.ImageResource { .init(name: "images/category/english/english", path: ["images", "category", "english"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/english/englishTest`.
          var englishTest: RswiftResources.ImageResource { .init(name: "images/category/english/englishTest", path: ["images", "category", "english"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }

        /// This `_R.image.images.category.finance` struct is generated, and contains static references to 2 finances.
        struct finance {
          let bundle: Foundation.Bundle

          /// Image `images/category/finance/accountant`.
          var accountant: RswiftResources.ImageResource { .init(name: "images/category/finance/accountant", path: ["images", "category", "finance"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/finance/finance`.
          var finance: RswiftResources.ImageResource { .init(name: "images/category/finance/finance", path: ["images", "category", "finance"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }

        /// This `_R.image.images.category.investment` struct is generated, and contains static references to 1 investments.
        struct investment {
          let bundle: Foundation.Bundle

          /// Image `images/category/investment/invest`.
          var invest: RswiftResources.ImageResource { .init(name: "images/category/investment/invest", path: ["images", "category", "investment"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }

        /// This `_R.image.images.category.law` struct is generated, and contains static references to 2 laws.
        struct law {
          let bundle: Foundation.Bundle

          /// Image `images/category/law/law`.
          var law: RswiftResources.ImageResource { .init(name: "images/category/law/law", path: ["images", "category", "law"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/law/promise`.
          var promise: RswiftResources.ImageResource { .init(name: "images/category/law/promise", path: ["images", "category", "law"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }

        /// This `_R.image.images.category.technology` struct is generated, and contains static references to 4 technologys.
        struct technology {
          let bundle: Foundation.Bundle

          /// Image `images/category/technology/ai`.
          var ai: RswiftResources.ImageResource { .init(name: "images/category/technology/ai", path: ["images", "category", "technology"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/technology/basicInformation`.
          var basicInformation: RswiftResources.ImageResource { .init(name: "images/category/technology/basicInformation", path: ["images", "category", "technology"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/technology/computer`.
          var computer: RswiftResources.ImageResource { .init(name: "images/category/technology/computer", path: ["images", "category", "technology"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/category/technology/programming`.
          var programming: RswiftResources.ImageResource { .init(name: "images/category/technology/programming", path: ["images", "category", "technology"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
      }

      /// This `_R.image.images.header` struct is generated, and contains static references to 0 headers, and 2 namespaces.
      struct header {
        let bundle: Foundation.Bundle
        var main_home: main_home { .init(bundle: bundle) }
        var request_home: request_home { .init(bundle: bundle) }

        func main_home(bundle: Foundation.Bundle) -> main_home {
          .init(bundle: bundle)
        }
        func request_home(bundle: Foundation.Bundle) -> request_home {
          .init(bundle: bundle)
        }


        /// This `_R.image.images.header.main_home` struct is generated, and contains static references to 3 main_homes.
        struct main_home {
          let bundle: Foundation.Bundle

          /// Image `images/header/main_home/header_first`.
          var header_first: RswiftResources.ImageResource { .init(name: "images/header/main_home/header_first", path: ["images", "header", "main_home"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/header/main_home/header_second`.
          var header_second: RswiftResources.ImageResource { .init(name: "images/header/main_home/header_second", path: ["images", "header", "main_home"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/header/main_home/header_third`.
          var header_third: RswiftResources.ImageResource { .init(name: "images/header/main_home/header_third", path: ["images", "header", "main_home"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }

        /// This `_R.image.images.header.request_home` struct is generated, and contains static references to 2 request_homes.
        struct request_home {
          let bundle: Foundation.Bundle

          /// Image `images/header/request_home/request_header`.
          var request_header: RswiftResources.ImageResource { .init(name: "images/header/request_home/request_header", path: ["images", "header", "request_home"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/header/request_home/request_header_background`.
          var request_header_background: RswiftResources.ImageResource { .init(name: "images/header/request_home/request_header_background", path: ["images", "header", "request_home"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
      }

      /// This `_R.image.images.onboarding` struct is generated, and contains static references to 3 onboardings.
      struct onboarding {
        let bundle: Foundation.Bundle

        /// Image `images/onboarding/onboarding_first`.
        var onboarding_first: RswiftResources.ImageResource { .init(name: "images/onboarding/onboarding_first", path: ["images", "onboarding"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/onboarding/onboarding_second`.
        var onboarding_second: RswiftResources.ImageResource { .init(name: "images/onboarding/onboarding_second", path: ["images", "onboarding"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/onboarding/onboarding_third`.
        var onboarding_third: RswiftResources.ImageResource { .init(name: "images/onboarding/onboarding_third", path: ["images", "onboarding"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.images.others` struct is generated, and contains static references to 7 otherss.
      struct others {
        let bundle: Foundation.Bundle

        /// Image `images/others/HITOKOMA`.
        var hitokomA: RswiftResources.ImageResource { .init(name: "images/others/HITOKOMA", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/applicationImage`.
        var applicationImage: RswiftResources.ImageResource { .init(name: "images/others/applicationImage", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/noHeaderImage`.
        var noHeaderImage: RswiftResources.ImageResource { .init(name: "images/others/noHeaderImage", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/noImage`.
        var noImage: RswiftResources.ImageResource { .init(name: "images/others/noImage", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/ramen`.
        var ramen: RswiftResources.ImageResource { .init(name: "images/others/ramen", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/rootImage`.
        var rootImage: RswiftResources.ImageResource { .init(name: "images/others/rootImage", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `images/others/teachBigin`.
        var teachBigin: RswiftResources.ImageResource { .init(name: "images/others/teachBigin", path: ["images", "others"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }

      /// This `_R.image.images.setting` struct is generated, and contains static references to 0 settings, and 1 namespaces.
      struct setting {
        let bundle: Foundation.Bundle
        var profile: profile { .init(bundle: bundle) }

        func profile(bundle: Foundation.Bundle) -> profile {
          .init(bundle: bundle)
        }


        /// This `_R.image.images.setting.profile` struct is generated, and contains static references to 5 profiles, and 1 namespaces.
        struct profile {
          let bundle: Foundation.Bundle

          /// Image `images/Setting/Profile/mail`.
          var mail: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/mail", path: ["images", "Setting", "Profile"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/Setting/Profile/man`.
          var man: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/man", path: ["images", "Setting", "Profile"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/Setting/Profile/password`.
          var password: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/password", path: ["images", "Setting", "Profile"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/Setting/Profile/profile`.
          var profile: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/profile", path: ["images", "Setting", "Profile"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

          /// Image `images/Setting/Profile/woman`.
          var woman: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/woman", path: ["images", "Setting", "Profile"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
          var snsIcon: snsIcon { .init(bundle: bundle) }

          func snsIcon(bundle: Foundation.Bundle) -> snsIcon {
            .init(bundle: bundle)
          }


          /// This `_R.image.images.setting.profile.snsIcon` struct is generated, and contains static references to 3 snsIcons.
          struct snsIcon {
            let bundle: Foundation.Bundle

            /// Image `images/Setting/Profile/SNSIcon/Twitter`.
            var twitter: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/SNSIcon/Twitter", path: ["images", "Setting", "Profile", "SNSIcon"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

            /// Image `images/Setting/Profile/SNSIcon/facebook`.
            var facebook: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/SNSIcon/facebook", path: ["images", "Setting", "Profile", "SNSIcon"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

            /// Image `images/Setting/Profile/SNSIcon/instagram`.
            var instagram: RswiftResources.ImageResource { .init(name: "images/Setting/Profile/SNSIcon/instagram", path: ["images", "Setting", "Profile", "SNSIcon"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
          }
        }
      }
    }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 2 properties.
  struct entitlements {
    let apsEnvironment: String = "development"
    let comAppleDeveloperApplesignin = comAppleDeveloperApplesignin()
    let comAppleDeveloperInAppPayments = comAppleDeveloperInAppPayments()
    struct comAppleDeveloperApplesignin {
      let `default`: String = "Default"
    }
    struct comAppleDeveloperInAppPayments {
      let merchantComHITOKOMA: String = "merchant.com.HITOKOMA"
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "HITOKOMA", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'HITOKOMA' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }
  }
}